name: Setup
description: Setup the development environment

runs:
  using: "composite"
  steps:
    - name: Setup Node.js and Bun
      uses: jdx/mise-action@e3d7b8d67a7958d1207f6ed871e83b1ea780e7b0 # v3
      with:
        cache: false

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile
