name: Setup
description: Setup the development environment

runs:
  using: "composite"
  steps:
    # See: https://turborepo.com/docs/guides/ci-vendors/github-actions#remote-caching-with-github-actionscache
    - name: Cache turbo build setup
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - name: Setup Node.js and Bun
      uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile
