name: Setup
description: Setup the development environment

runs:
  using: "composite"
  steps:
    - name: Setup Node.js and Bun
      uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3
      with:
        cache: false

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile
