name: Utility commands

on:
  issue_comment:
    types:
      - created

jobs:
  install:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/install')
    permissions:
      contents: write
      pull-requests: write
      issues: read
    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch
      - name: Checkout repository
        uses: actions/checkout@v4
        if: success()
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
      - name: Setup tools
        uses: jdx/mise-action@v2
      - name: Install dependencies
        run: bun install
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(deps): fix lockfile"
